# Generated by Django 5.0.6 on 2024-07-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='album',
            name='genre',
        ),
        migrations.AlterField(
            model_name='user',
            name='albums',
            field=models.ManyToManyField(blank=True, related_name='users', to='base.album'),
        ),
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='albums', to='base.genre'),
        ),
    ]
