# Generated by Django 5.0.6 on 2024-07-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_genre_remove_album_genre_alter_user_albums_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='activeyears',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='genre',
        ),
        migrations.AddField(
            model_name='album',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
