# Generated by Django 5.0.6 on 2024-07-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_artist_activeyears_remove_artist_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
