# Generated by Django 5.0.6 on 2024-08-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_type_album_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='album',
            name='type',
        ),
        migrations.AddField(
            model_name='album',
            name='format',
            field=models.ManyToManyField(blank=True, related_name='albums', to='base.format'),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
