# Generated by Django 5.0.6 on 2024-08-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_show_remove_album_format_delete_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='showdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
