# Generated by Django 5.0.6 on 2024-08-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_show_showdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
