# Generated by Django 5.0.6 on 2024-08-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='album',
            name='file',
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='songs/'),
        ),
    ]
