# Generated by Django 5.0.6 on 2024-08-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_album_audio_remove_album_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
