# Generated by Django 5.1 on 2024-08-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_artist_bio_artist_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
