# Generated by Django 5.1 on 2024-08-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_show_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='artist',
            field=models.ManyToManyField(blank=True, related_name='albums', to='base.artist'),
        ),
    ]
