# Generated by Django 5.1 on 2024-08-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_show_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='show',
            field=models.ManyToManyField(blank=True, related_name='perf_artist', to='base.show'),
        ),
        migrations.AlterField(
            model_name='show',
            name='artist',
            field=models.ManyToManyField(blank=True, related_name='shows', to='base.artist'),
        ),
    ]
