# Generated by Django 5.1 on 2024-08-13 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_artist_show_alter_show_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='artist',
        ),
        migrations.AddField(
            model_name='show',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shows', to='base.artist'),
        ),
    ]
